### ISSUE TITLE
MVP node + wallet

### ISSUE THREAD

**Issue by torkelrogstad** [bitcoin-s/bitcoin-s#530]
This is an umbrella issue for all functionality needed for our SPV node + wallet combo to be a shippable software package (at least for expert users). Please don't submit any PRs that close this issue, rather create sub issues for each item on these lists, and then PRs that close those. Feel free to comment/edit this issue with further things that need to be added.

## Node

- [ ] Connect to multiple peers at the same time
- [ ] Bootstrap with DNS seeds, without explicitly passing in a peer
- [ ] Verify Merkle blocks/proofs
- [x] Handle reorgs (#453)
- [ ] Segwit/newer than 24 months P2P messages

## Wallet

- [x] Add API for importing transactions (#534)
- [x] Extend `processTransaction` to also handle outgoing TXs (#555)
- [ ] Sweeping private keys/seeds
- [ ] Handling reorgs
- [ ] Coin selection (partially fixed by #431)
- [ ] Managing change UTXOs correctly when spending (#555)
- [x] Manage UTXOs in DB correctly when spending (#538)
- [ ] Handle double-spends

## CLI/external communication

Open questions:

- [ ] How do we serve requests in the wallet/node? #536 
- [ ] How do we handle authentication?
- [x] In what language do we write the CLI? Scala has slow JVM startup, but if we can
      use Scala Native/GraalVM AOT compilation we could get it to work  
       **UPDATE**: I wrote a very basic PoC that exposes a nice CLI interface
      and AOT-compiles with GraalVM `native-image`. Link:
      https://github.com/torkelrogstad/bitcoin-s/commit/8898320e25e712b5b91c50801d990a974b6d7882
